### ISSUE TITLE
Can't run  Anyphone IOS

### ISSUE THREAD

**Issue by nexslab** [ParsePlatform/AnyPhone#14]
Can anyone help me just new in this stuff. Thanks!
After the step in description i get this error. i'm using the new Xcode beta with  El capitano

When i'm try to run the Anyphone sample code i get :
error 1 : 
ld: -undefined and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together
clang: error: linker command failed with exit code 1 (use -v to see invocation)

erro 2: 
AnyPhone-master/AnyPhone/AnyPhone/LoginViewController.swift:75:15: Cannot invoke 'callFunctionInBackground' with an argument list of type '(String, withParameters: [String : String?], (AnyObject?, NSError?) -> Void)'

**Comment by gfosco** [comment]
Try using Xcode 6.4... This hasn't been tested/used with 7 beta yet.

**Comment by nexslab** [comment]
Hi thanks for the quick reply. Unfortunately  Xcode 6.4.. do not work anymore(is not compatible) on Mac Os El Capitan.

**Comment by gfosco** [comment]
Sure it does.. I am running 10.11 and both 6.4 and 7 beta.
![El Cap running both Xcodes](http://i.imgur.com/jyZoqba.png)

**Comment by nlutsenko** [comment]
It looks like if you simply disable bitcode in build settings it should work.

**Comment by hramos** [comment]
This should be solved by disabling bitcode as stated in the error message. Closing.
