### ISSUE TITLE
Not getting verification code

### ISSUE THREAD

**Issue by FezHacker** [ParsePlatform/AnyPhone#17]
Not getting verification code

**Comment by gfosco** [comment]
There could be many reasons for this, and you've not provided enough information.  Try troubleshooting and determining where the problem is.

**Comment by FezHacker** [comment]
I found out the answer the parse cloud code was incorrect.

The problem was that when a New user submitted their phone number is was
not sending the text because it didn't return the smsCode in code.

**Comment by gfosco** [comment]
ah.. just merged that PR, yeah.. sorry.
