### ISSUE TITLE
Can't run Anyphone- Android

### ISSUE THREAD

**Issue by mbellamk** [ParsePlatform/AnyPhone#18]
Hi,

when i have imported the Anyphone-Android project into my eclipse it is showing error
"error: Error retrieving parent for item: No resource found that matches the given name 
 'Theme.AppCompat.Light.NoActionBar'."
Please give me suggestions how to resolve it.

**Comment by madhavc** [comment]
File->Import (android-sdk\extras\android\support\v7). Choose "appcompat"
Project-> properties->Android. In the section library "Add" and choose "appCompat"
That is all!
