### ISSUE TITLE
ios cocoapods install fail

### ISSUE THREAD

**Issue by ruandao** [ParsePlatform/AnyPhone#19]
Sending stats
      - Bolts, 1.1.5
      - Parse, 1.7.4
      - ParseUI, 1.1.4
      Failed to send stats:  SSL_connect returned=1 errno=0 state=SSLv2/v3 read
      server hello A: sslv3 alert handshake failure

May be package the whole pods to the project is a good choice for demo project

**Comment by gfosco** [comment]
Sounds like a temporary https issue you're having, unrelated to this project... Try again.

**Comment by ruandao** [comment]
was it posibile to add all pod module to git repositories

I think, many people like me who live in china, may face this problem

the fuck gfw, make the network unstable

**Comment by gfosco** [comment]
We've stopped adding the modules to the sample repos because they fall out of date quickly and we don't want to keep updating them.  Cocoapods allows the samples to stay current.

**Comment by ruandao** [comment]
get
