### ISSUE TITLE
Login Function Response

### ISSUE THREAD

**Issue by timigod** [ParsePlatform/AnyPhone#25]
In main.js for, the login function response is user._sessionToken which obviously doesn't return anything. Should be user.getSessionToken().
Took a while to figure out why it was crashing.

**Comment by maodd** [comment]
confirmed. thanks for saving my day!

**Comment by danglade** [comment]
Wow man, thank you! Been more than 4 hours with this

**Comment by LucaDe** [comment]
Thank you!!! Had nice 4-5 hours trying to handle this error :)

**Comment by gfosco** [comment]
Fixed with #30
