### ISSUE TITLE
Login Error - function not found

### ISSUE THREAD

**Issue by OptTrader** [ParsePlatform/AnyPhone#31]
After I ran Parse deploy at the Cloud folder on the terminal - I see the following;

Uploading source files
Finished uploading files
Not creating a release because no files have changed

When I ran the app with the phone number I got from Twilio to test - I get a Login Error with function not found message.

What did I do wrong?

**Comment by gfosco** [comment]
Make sure that everything is correct with regards to your parse app id... Check in the dashboard, Data -> Cloud Code area to see if the code shows up there... Make a change to the cloud files and deploy again.  Re-open if you don't figure it out, thanks.

**Comment by sujithv28** [comment]
For the phone Number do we add the +1 or just leave the 10 digit number?
