### ISSUE TITLE
AnyPhone cloud code on Heroku

### ISSUE THREAD

**Issue by bradfol** [ParsePlatform/AnyPhone#32]
I'm trying to get this demo cloud code running on Heroku using the integration built into the Parse CLI.

Changes I've made so far:
* `bodyParser` is no longer included in Express. Require it separately.
* Add `twilio` to npm package dependencies.
* Require the `Parse` module from `parse-cloud-express`.

I'm attempting to push to Heroku, but it is hanging on the deploy after this point:
```
remote:        Hooks registration completed.
remote:        Registered function for: logIn
remote:        Registered function for: sendCode
```

Any suggested troubleshooting steps?

**Comment by bradfol** [comment]
Here is the repo I'm pushing to Heroku:
https://github.com/bradfol/AnyPhone-Heroku

**Comment by gfosco** [comment]
Can you set the environment variables and run node scripts/register-webhooks.js locally?  If that fails, add some logging to the various steps?

**Comment by bradfol** [comment]
@gfosco 
It seems this was caused by both `server.js` and `cloud/app.js` creating express app instances. It would launch locally in node, but would not deploy to Heroku. I moved all express setup code to `server.js` (https://github.com/bradfol/AnyPhone-Heroku/commit/3968e8bf1cb5d703ff05024338a1b8c8fbc3f1e5) and now it deploys to Heroku.

I'm getting closer to having this up and running, but now hitting an issue with the `logIn` cloud function:
```
Error: It is not memory-safe to become a user in a server environment
```
Is it going to be possible to do the user login in the node environment (as opposed to the original cloud code environment)?

**Comment by gfosco** [comment]
So the error is correct there, you should not use login/signup/become in a server environment.  Once you have the session token, you should pass it as an option during operations to use it.  i.e, during a query, `query.find({ sessionToken: mytoken });` or during a save, `obj.save({}, { sessionToken: mytoken });`

**Comment by bradfol** [comment]
Thanks for your help @gfosco
